apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 8080        # Port exposed by the service
    targetPort: 80    # Port on the pod where traffic is sent
    nodePort: 31000   # Optional: NodePort is still valid but not required for LoadBalancer
  selector:
    app: vote
